name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - voici>=0.3.2,<0.4.0
    - jupyterlite-xeus-python>=0.8.0,<0.9.0
    - numpy==1.23.1
    - opencv-contrib-python==4.6.0.66

