name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pandas
  - bqplot
  - pillow
  - matplotlib
  - pip=22.1.2
  - pip :
      - numpy=1.23.1
      - opencv-contrib-python==4.6.0.66


